# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.3
  slack: circleci/slack@4.8.3
jobs:
  test:
    docker:
      - image: cimg/openjdk:20.0-browsers
    resource_class: xlarge
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - run: |
            google-chrome --version
            java --version
            ls -la
            mkdir -p https/testimages.luxyride.com/screenshots
      - run: |
            curl https://downloads.lambdatest.com/hyperexecute/linux/hyperexecute
            chmod u+x ./hyperexecute 
    #        ls -la
            ./hyperexecute --user hvudutala --key Wz4cMuQW16k1ZB8Uqp0I3pRU4x3zKRD5WGhCRwZerNOOe2pZ8f --config Config/"$type"_TestRunConfig/"$ENV"/"$ENV""$type"_TestRun_"$testtype"_"$os".yaml --vars "browser="$browser"" -v
    #         +x = add and grant execute permissions        
    #        rm -f ./hyperexecute
      - run: |
          mkdir -p tmp/artifacts
          ls -la
          cp -R https:/testimages.luxyride.com/screenshots tmp/artifacts/screenshots || true
          cp -R test-output tmp/artifacts/test-output || true
  #        cp test-output/Luxy*.html index.html || true
  #       zip -r artifacts-"$env"-"$testtype"-$(date +"%Y-%m-%d-%H:%M:%S").zip tmp
      - run:
          name: installing AWS Cli
          working_directory: /
          command: |
            sudo curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.0.30.zip" -o "awscliv2.zip"
            sudo unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Deploy to s3
          command: |
            aws --region us-east-1 s3 sync https:/testimages.luxyride.com/screenshots s3://luxy-test-automation/screenshots || true
            aws --region us-east-1 s3 sync test-output s3://luxy-test-automation/test-output || true
      - run:
          name: Invalidate cloudfront cache
          command: |
            AWS_PAGER="" aws cloudfront create-invalidation --distribution-id E3P66F0AYP3GJZ --paths /\*
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
      - slack/notify:
          event: pass
          custom: |
            {
                        	"text": "",
                        	"blocks": [
                        		{
                        			"type": "header",
                        			"text": {
                        				"type": "plain_text",
                        				"text": "${ENV} ${testtype} Automation Successful! :tada:",
                        				"emoji": true
                        			}
                        		},
                        		{
                        			"type": "actions",
                        			"elements": [
                        				{
                        					"type": "button",
                        					"text": {
                        						"type": "plain_text",
                        						"text": "View Report"
                        					},
                        					"url": "https://testreport.luxyride.com/"
                        				}
                        			]
                        		}
                        	]
                        }
workflows:
  DEV-Sanity: 
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - sanity
                - dev
                - userportal
                - chrome
                - windows
          filters:
            tags:
              only: /^devchrome.20.*/
            branches:
              ignore: /.*/

  dev-userportal-sanity-chrome:
    when:
      equal: [ dev-userportal-sanity-chrome, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - sanity
                - userportal
                - dev
                - chrome
                - windows
  dev-userportal-sanity-safari:
    when:
      equal: [ dev-userportal-sanity-safari, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - sanity
                - userportal
                - dev
                - safari
                - mac
  dev-userportal-regression-chrome:
    when:
      equal: [ dev-userportal-regression-chrome, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - regression
                - userportal
                - dev
                - chrome
                - windows
  dev-userportal-regression-safari:
    when:
      equal: [ dev-userportal-regression-safari, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - regression
                - userportal
                - dev
                - safari
                - mac
  uat-userportal-sanity-chrome:
    when:
      equal: [ uat-userportal-sanity-chrome, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - sanity
                - userportal
                - uat
                - chrome
                - windows
  uat-userportal-sanity-safari:
    when:
      equal: [ uat-userportal-sanity-safari, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - sanity
                - userportal
                - uat
                - safari
                - mac
  uat-userportal-regression-chrome:
    when:
      equal: [ uat-userportal-regression-chrome, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - regression
                - userportal
                - uat
                - chrome
                - windows
  uat-userportal-regression-safari:
    when:
      equal: [ uat-userportal-regression-safari, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - regression
                - userportal
                - uat
                - safari
                - mac
  prod-userportal-sanity-chrome:
    when:
      equal: [ prod-userportal-sanity-chrome, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - sanity
                - userportal
                - prod
                - chrome
                - windows
  prod-userportal-sanity-safari:
    when:
      equal: [ prod-userportal-sanity-safari, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - sanity
                - userportal
                - prod
                - safari
                - mac
  prod-userportal-regression-chrome:
    when:
      equal: [ prod-userportal-regression-chrome, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - regression
                - userportal
                - prod
                - chrome
                - windows
  prod-userportal-regression-safari:
    when:
      equal: [ prod-userportal-regression-safari, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - regression
                - userportal
                - prod
                - safari
                - mac
  dev-dispatch-sanity-chrome:
    when:
      equal: [ dev-dispatch-sanity-chrome, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - sanity
                - dispatch
                - dev
                - chrome
                - windows
  dev-dispatch-sanity-safari:
    when:
      equal: [ dev-dispatch-sanity-safari, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - sanity
                - dispatch
                - dev
                - safari
                - mac
  
  dev-dispatch-regression-chrome:
    when:
      equal: [ dev-dispatch-regression-chrome, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - regression
                - dispatch
                - dev
                - chrome
                - windows
  dev-dispatch-regression-safari:
    when:
      equal: [ dev-dispatch-regression-safari, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - regression
                - dispatch
                - dev
                - safari
                - mac
 

  uat-dispatch-regression-chrome:
    when:
      equal: [ uat-dispatch-regression-chrome, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - regression
                - dispatch
                - uat
                - chrome
                - windows
  uat-dispatch-regression-safari:
    when:
      equal: [ uat-dispatch-regression-safari, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - regression
                - dispatch
                - uat
                - safari
                - mac

  prod-dispatch-regression-chrome:
    when:
      equal: [ prod-dispatch-regression-chrome, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - regression
                - dispatch
                - prod
                - chrome
                - windows
  prod-dispatch-regression-safari:
    when:
      equal: [ prod-dispatch-regression-safari, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - regression
                - dispatch
                - prod
                - safari
                - mac
  dev-concierge-sanity-chrome:
    when:
      equal: [ dev-concierge-sanity-chrome, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - sanity
                - concierge
                - dev
                - chrome
                - windows
  dev-concierge-sanity-safari:
    when:
      equal: [ dev-concierge-sanity-safari, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - sanity
                - concierge
                - dev
                - safari
                - mac
  
  dev-concierge-regression-chrome:
    when:
      equal: [ dev-concierge-regression-chrome, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - regression
                - concierge
                - dev
                - chrome
                - windows
  dev-concierge-regression-safari:
    when:
      equal: [ dev-concierge-regression-safari, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - regression
                - concierge
                - dev
                - safari
                - mac
  uat-concierge-regression-chrome:
    when:
      equal: [ uat-concierge-regression-chrome, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - regression
                - concierge
                - uat
                - chrome
                - windows
  uat-concierge-regression-safari:
    when:
      equal: [ uat-concierge-regression-safari, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - regression
                - concierge
                - uat
                - safari
                - mac
  prod-concierge-regression-chrome:
    when:
      equal: [ prod-concierge-regression-chrome, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - regression
                - concierge
                - prod
                - chrome
                - windows
  prod-concierge-regression-safari:
    when:
      equal: [ prod-concierge-regression-safari, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - regression
                - concierge
                - prod
                - safari
                - mac
  dev-travelagent-sanity-chrome:
    when:
      equal: [ dev-travelagent-sanity-chrome, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - sanity
                - travelagent
                - dev
                - chrome
                - windows
  dev-travelagent-sanity-safari:
    when:
      equal: [ dev-travelagent-sanity-safari, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - sanity
                - travelagent
                - dev
                - safari
                - mac
  
  dev-travelagent-regression-chrome:
    when:
      equal: [ dev-travelagent-regression-chrome, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - regression
                - travelagent
                - dev
                - chrome
                - windows
  dev-travelagent-regression-safari:
    when:
      equal: [ dev-travelagent-regression-safari, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - regression
                - travelagent
                - dev
                - safari
                - mac
  uat-travelagent-regression-chrome:
    when:
      equal: [ uat-travelagent-regression-chrome, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - regression
                - travelagent
                - uat
                - chrome
                - windows
  uat-travelagent-regression-safari:
    when:
      equal: [ uat-travelagent-regression-safari, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - regression
                - travelagent
                - uat
                - safari
                - mac
  prod-travelagent-regression-chrome:
    when:
      equal: [ prod-travelagent-regression-chrome, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - regression
                - travelagent
                - prod
                - chrome
                - windows
  prod-travelagent-regression-safari:
    when:
      equal: [ prod-travelagent-regression-safari, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - regression
                - travelagent
                - prod
                - safari
                - mac
  uat-affiliate-regression-chrome:
    when:
      equal: [ uat-affiliate-regression-chrome, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - regression
                - affiliate
                - uat
                - chrome
                - windows
  uat-affiliate-regression-safari:
    when:
      equal: [ uat-affiliate-regression-safari, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - regression
                - affiliate
                - uat
                - safari
                - mac
  dev-affiliate-sanity-chrome:
    when:
      equal: [ dev-affiliate-sanity-chrome, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - sanity
                - affiliate
                - dev
                - chrome
                - windows
  dev-affiliate-sanity-safari:
    when:
      equal: [ dev-affiliate-sanity-safari, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - sanity
                - affiliate
                - dev
                - safari
                - mac
  dev-affiliate-regression-chrome:
    when:
      equal: [ dev-affiliate-regression-chrome, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - regression
                - affiliate
                - dev
                - chrome
                - windows
  dev-affiliate-regression-safari:
    when:
      equal: [ dev-affiliate-regression-safari, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - regression
                - affiliate
                - dev
                - safari
                - mac
  prod-affiliate-regression-chrome:
    when:
      equal: [ prod-affiliate-regression-chrome, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - regression
                - affiliate
                - prod
                - chrome
                - windows
  prod-affiliate-regression-safari:
    when:
      equal: [ prod-affiliate-regression-safari, << pipeline.schedule.name >> ]
    jobs:
      - test:
          context: 
                - aws-lower-env
                - slack-secrets
                - regression
                - affiliate
                - prod
                - safari
                - mac