
version: 0.1
runson: win11

##Minutes
globalTimeout: 150
testSuiteTimeout: 150
testSuiteStep: 150

autosplit: true
concurrency: 1

pre:
  - mvn dependency:resolve -Dmaven.repo.local=./.m2
  - npm install fs xml2js
  
cacheKey: '{{ checksum "pom.xml" }}'
cacheDirectories:
  - .m2
  
testDiscovery:
  type: raw
  mode: dynamic
  command: node discovery.js Config/dispatch_TestRunConfig/uat/uatdispatch_TestRun_Regression.xml
  
testRunnerCommand:  mvn test `-Dmaven.repo.local=./.m2 `-Dtest=$test `-Dsurefire.suiteXmlFiles=Config/dispatch_TestRunConfig/uat/uatdispatch_TestRun_Regression.xml `-Dbrowser=${browser} `-Denvironment=uatdispatch

retryOnFailure: true
maxRetries: 1

runtime:
   language: java
   version: 20

project:
   name: UAT_Dispatch_TestRun_Regression_Windows11_Chrome
differentialUpload:
   enabled: true
   ttlHours: 25
   
report: true
partialReports:
  location: test-output/
  frameworkName: extent
  type: html

jobLabel: ['UAT_Dispatch_TestRun_Regression_Windows11_${browser}']