
version: 0.2
runson: win11

autosplit: true
concurrency: 1

pre:
- mvn dependency:resolve
framework:

   name: maven/testng
# Skip execution of the tests in the pre step
   flags:
   - -Dsurefire.suiteXmlFiles=Config/userportal_TestRunConfig/dev/devuserportal_TestRun_Regression.xml
   - -Dbrowser=${browser}
   discoveryType: class
   defaultReports: false
## - "-Dgroups=selenium-test"

retryOnFailure: true
maxRetries: 1

runtime:
   language: java
   version: 20

project:
   name: DEV_Userportal_TestRun_Regression_Windows11_Chrome
differentialUpload:
   enabled: true
   ttlHours: 2

report: true

jobLabel: ['DEV_Userportal_TestRun_Regression_Windows11_${browser}']

partialReports:
  location: test-output/
  frameworkName: extent
  type: html