
version: 0.2
runson: mac

autosplit: true
concurrency: 1

pre:
- mvn dependency:resolve
framework:

   name: maven/testng
# Skip execution of the tests in the pre step
   flags:
   - -Dsurefire.suiteXmlFiles=../luxy-automation-multi-platform-lambdatest/Config/userportal_TestRunConfig/dev/devuserportal_TestRun_Sanity.xml
   - -Dbrowser=${browser}
   discoveryType: class
   defaultReports: false
## - "-Dgroups=selenium-test"

retryOnFailure: true
maxRetries: 1

runtime:
   language: java
   version: 20

project:
   name: DEV_Userportal_TestRun_Sanity_macOS_Safari
differentialUpload:
   enabled: true
   ttlHours: 2

report: true

jobLabel: ['DEV_Userportal_TestRun_Sanity_macOS_${browser}']

partialReports:
  location: test-output/
  frameworkName: extent
  type: html