---
version: 0.1
runson: mac13

autosplit: true
concurrency: 1

pre:
  - mvn dependency:resolve -Dmaven.repo.local=./.m2
  - npm install fs xml2js
  
testDiscovery:
  type: raw
  mode: dynamic
  command: node discovery.js Config/userportal_TestRunConfig/dev/devuserportal_TestRun_Regression.xml
  
testRunnerCommand:  mvn test `-Dmaven.repo.local=./.m2 `-Dtest=$test `-Dsurefire.suiteXmlFiles=Config/userportal_TestRunConfig/dev/devuserportal_TestRun_Regression.xml `-Dbrowser=${browser} `-Denvironment=devuserportal

retryOnFailure: true
maxRetries: 1

runtime:
   language: java
   version: 20

project:
   name: DEV_Userportal_TestRun_Regression_MacOS_Safari
differentialUpload:
   enabled: true
   ttlHours: 25
   
report: true
partialReports:
  location: test-output/
  frameworkName: extent
  type: html

jobLabel: ['DEV_Userportal_TestRun_Regression_MacOS_${browser}']