
version: 0.2
runson: mac13

autosplit: true
concurrency: 1

pre:
- mvn dependency:resolve
framework:

   name: maven/testng
# Skip execution of the tests in the pre step
   flags:
   - -Dsurefire.suiteXmlFiles=../luxy-automation-multi-platform-lambdatest/Config/dispatch_TestRunConfig/dev/devdispatch_TestRun_Regression.xml
   - -Dbrowser=${browser}
   discoveryType: class
   defaultReports: false
## - "-Dgroups=selenium-test"

retryOnFailure: true
maxRetries: 1

runtime:
   language: java
   version: 20

project:
   name: Dispatch_TestRun_Regression_macOS_Safari
differentialUpload:
   enabled: true
   ttlHours: 2

report: true

jobLabel: ['LuxyDispatch_Regression_DEV_macOS13_${browser}']

partialReports:
  location: test-output/
  frameworkName: extent
  type: html