version: 0.1
runson: mac13

##Minutes
globalTimeout: 150
testSuiteTimeout: 150
testSuiteStep: 150

autosplit: true
concurrency: 1

pre:
  - mvn dependency:resolve -Dmaven.repo.local=./.m2
  - npm install fs xml2js
  
cacheKey: '{{ checksum "pom.xml" }}'
cacheDirectories:
  - .m2
      
testDiscovery:
  type: raw
  mode: dynamic
  command: node discovery.js Config/concierge_TestRunConfig/uat/uatconcierge_TestRun_Regression.xml
  
testRunnerCommand:  mvn test -Dmaven.repo.local=./.m2 -Dtest=$test -Dsurefire.suiteXmlFiles=Config/concierge_TestRunConfig/uat/uatconcierge_TestRun_Regression.xml -Dbrowser=${browser} -Denvironment=uatconcierge

retryOnFailure: false
maxRetries: 1

runtime:
   language: java
   version: 20

project:
   name: UAT_Concierge_TestRun_Regression_MacOS_Safari
differentialUpload:
   enabled: true
   ttlHours: 25
   
report: true
partialReports:
  location: test-output/
  frameworkName: extent
  type: html

jobLabel: ['UAT_Concierge_TestRun_Regression_MacOS_${browser}']